### ISSUE TITLE
High memory utilization

### ISSUE THREAD

**Issue by Miggleness** [JasperFx/lamar#102]
### Problem
I'm getting high memory usage showing up in Visual Studio 2017 debug diagnostics after simply switching to Lamar 1.1.2 in my ASP.NET core 2.1 project.

| IoC | Process Memory (MB) |
| --- | ------------------------- |
| Built-in | 74 - 90 MB |
| Lamar | 600 - 900 MB |

I use the following
- ASP.NET Core 2.1 on .NET Framework 4.7.2
- AutoMapper 7.0.1
- Hangfire 1.6.20
- Lamar 1.1.2
- Newtonsoft.Json 11.0.2
- WorkflowCore 1.6.8

_What Do I Have Report_ : https://gist.github.com/Miggleness/6781698657a9cfbd6dd067cc20acd377

### Root Cause
I haven't gone deep in investigating why this is happening.  Will post an update here if any.

**Comment by mikejr83** [comment]
Not to be another "me too" comment, but I'm seeing something similar, although my setup is a bit different than yours:

* .NET Core 2.0
* ASP.NET Core 2.0.7
* AutoMapper 6.2.2
* Hangfire 1.6.20
* Lamar 1.1.2
* Newtonsoft (but not explicitly)

I spoke with @jeremydmiller in the gitter chat. He mentioned that there was a report of high memory consumption in ASP.NET Core. I'm not sure if he was referring to this issue or not. 

One thing I find interesting is that we're both using Hangfire. Hangfire may be doing something interesting with how it is instantiating the classes for the jobs.

I'm going to go to one of my team's other API services where we've set it up just as a set of REST API endpoints and enable Lamar and see if I can grab a snapshot before and after. That should allow us to see if Hangfire is doing something odd under the hood.

BTW, @Miggleness, are you setting up Hangfire to use Lamar's container for JobActivator? I had implemented my own only to really see that DI was still happening. I kinda wanted to ask the Lamar team if there default implementation did something with `Activator.CreateInstance` which would allow Hanfire to automatically utilize the container.

**Comment by mikejr83** [comment]
Here is the application running for about a minute after the swagger UI shows up. Immediately after the page loaded I hit the memory snapshot button.
![image](https://user-images.githubusercontent.com/3267135/47853462-31419200-ddb5-11e8-804f-2c96f9ff97d1.png)

Here is the same when adding in Lamar, no other changes:
![image](https://user-images.githubusercontent.com/3267135/47853509-5b934f80-ddb5-11e8-9e3c-fe2124b4d3a5.png)

So this should confirm that Hangfire has nothing to do with the issue.

While doing this little experiment I noticed something very interesting. When I loaded up the application without Lamar the console app window was open showing the logging statements. The very typical of our API project output was displayed:

```
Hosting environment: Development
Content root path: C:\projects\cbes_background_records_api\BackgroundRecordsApi
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

```

Nothing unusual there. However, when I enabled Lamar it was like I had full logging enabled. I can't post the logs here because it has a bunch of sensitive stuff in the debug statements, but in the same time frame it generated 173 lines of output (not messages; line count from Notepad++).

I wonder if Lamar could be doing something interesting with diagnostics within ASP.NET Core.

**Comment by CodingGorilla** [comment]
I did some quick tests with one of our MVC (API) projects and I don't see any abnormal memory usage.  My memory utilization hovers around 9Mb after running several requests.  @mikejr83 mentioned the use of the Swagger UI, I am wondering if that's the culprit.  On my end, I don't use swagger at all, and the project runs on .NET Core (no full framework like @Miggleness).

**Comment by mikejr83** [comment]
Here's some other libraries that we're using that may need some investigation:

* AutoMapper
* NLog
* IdentityServer4

@CodingGorilla, in your API solution are you using any of these? I'm wondering if AutoMapper could be an issue.

**Comment by CodingGorilla** [comment]
I use AutoMapper, and SeriLog for logging, and no IdentityServer.

**Comment by CodingGorilla** [comment]
So here's my analysis with dotMemory, this was done just running the MVC project as a self-contained .exe from the command line.  The interesting thing to me is that when it starts up, there is ~1GB of memory utilization, but it's *almost all* unmanaged memory.  My overall managed memory utilization is just under 13Mb though.

![image](https://user-images.githubusercontent.com/570801/47857891-c8f4af80-ddb8-11e8-9f7e-6b1122accba0.png)

**Comment by mikejr83** [comment]
Ok. That kind of goes with the images I posted earlier that showed the heap around 5.5mb without Lamar and around 12mb with Lamar. The process consumption was around 144 vs. 1gb.

I just created a new .NET Core 2.1 with ASP.NET 2.1.1 and only added Lamar. Doing the same comparison was showing a process consumption of 70mb vs. about 1gb. I didn't grab the heap sizes.

You'll have to forgive me as I've really only ever dealt with manged memory, but what does it mean when the app is using all that additional memory as unmanaged memory?

**Comment by jeremydmiller** [comment]
I wonder how much of this would be the initial hit where it has to JIT the Roslyn assemblies. Not letting Lamar off the hook mind you, but still

**Comment by CodingGorilla** [comment]
@mikejr83 In this particular case, the unmanaged memory is probably the actual .net core runtime and the in process web server (Kestrel).

@jeremydmiller In my analysis, one thing I did notice was a lot of strings being held onto by Roslyn and Lamar, I would venture to guess that's the actual code building.

**Comment by jeremydmiller** [comment]
Yeah, but that should be let go after the initial construction and compilation. Do you at least see the memory being reclaimed?

And it's a little bit hokey, but Lamar has a not quite documented function where you can generate the resolver code upfront and load resolvers from pre-built types. All meant as a way to speed up cold starts in Jasper apps, but it should be valuable everywhere.

**Comment by CodingGorilla** [comment]
No, those were the top two (Roslyn and Lamar) on the list the entire time.  But, to be clear, it was like 7 or 8 Mb of strings, not anything to extra-ordinary.  And, as I mentioned before, my app's memory utilization seems perfectly normal.

**Comment by Miggleness** [comment]
Sorry, I wish I could contribute ot the investigation more but for now I switched to using the default.  Rather in a rush to finish my project.  I do suspect it's something to do with Roslyn, but a 10x increase in memory usage in debug mode is rather surprising.

**Comment by Miggleness** [comment]
Might be related to this issue https://github.com/dotnet/roslyn/issues/22219

**Comment by ben-foster-cko** [comment]
A number of our teams are also experiencing this with even a simple ASP.NET Core app hitting around 700mb utilisation on startup which hits the memory limits on our containers (usually we have these set to < 500mb). We're having to switch back to StructureMap for now.

**Comment by Miggleness** [comment]
I did try running csharpscript’s evaluate async in a loop over the same code string, and did see a huge chuck of memory allocation at each iteration. But i suppose the fix is not a priority now.

**Comment by jeremydmiller** [comment]
@Miggleness I'm gonna look a bit harder at caching the CSharpScript and see what changes. Well, and whether or not it works at all;)

**Comment by jeremydmiller** [comment]
@Miggleness And it's not that because we don't use it in `AssemblyGenerator`. Back to the drawing board.

**Comment by jeremydmiller** [comment]
Hey all, I think I'm going to punt this one to a future 2.0.1. I haven't been able to recreate it yet, but haven't tried hard enough. I've got a few ideas. Did update Roslyn dependencies too and wanna see how that goes

**Comment by thomasgassmann** [comment]
@jeremydmiller Is there any update on this?

**Comment by jeremydmiller** [comment]
Sigh, no. I don't have any information on either causes or usable memory dumps. We've had quite a few versions of the Roslyn infrastructure since then.

**Comment by jackl306** [comment]
We are experiencing the same issue, large memory consumption (around 800MB) ) by Lamar.

Our project is a simple .NET CORE 2.2 Web API but constantly uses about 800MB ram. 

Memory analyzer shows our API produces around 700M unmanaged memory usage that is not from our code. 
![memsum](https://user-images.githubusercontent.com/47540136/52592473-5614cd80-2eab-11e9-92d8-3cf65e57b07f.JPG)

The details shows majority of unmanaged memory usage is from system.reflection:
![mem2](https://user-images.githubusercontent.com/47540136/52592555-91170100-2eab-11e9-806f-921a5bb55eee.JPG)

We got no idea what was the root cause so we tried to remove third party dependencies to narrow down the root cause. Eventually as soon as we had Lamar removed, the memory consumption was down to 40MB.

**Comment by CodingGorilla** [comment]
The unmanaged memory is (I'm pretty sure) the Roslyn compiler doing it's thing.  In all of my testing that memory is freed up pretty quickly after the initial start up.  @jackl306  Are your tests done in Debug mode or Release mode?

**Comment by jeremydmiller** [comment]
@CodingGorilla @jackl306 I can scan the code for something we could be disposing that isn't today, but otherwise, it might be time to get some Roslyn team help on this one.

**Comment by jeremydmiller** [comment]
@jackl306 Any chance you could do a memory dump using something that will show the object types on the heap? Looking for references to `GeneratedAssembly` more than anything. That or `AssemblyGenerator`.

**Comment by CodingGorilla** [comment]
@jeremydmiller That probably wouldn't hurt, I am seeing more memory use in my environment than when this issue was initially opened.  Here's just a quick snapshot from a quick test if it helps at all:

![image](https://user-images.githubusercontent.com/570801/52595495-a2143380-2e13-11e9-972c-d0bbb20bd8ca.png)

**Comment by jeremydmiller** [comment]
None of that is crazy though. I'm thinking now that something goes wrong -- or something I'm not seeing yet -- is keeping a reference to an AssemblyGenerator, which has a reference to the Roslyn objects that were used to generate the dynamic assembly.

**Comment by danspam** [comment]
I was having a quick look at this yesterday. Running our application with StructureMap results in memory usage of 53MB whilst with a rough Lamar conversion, it results in 200MB memory usage. I did take a heap dump of both. Here is the Lamar version if it has an clues (I could not see anything obvious)

[dumpheap-stat.txt](https://github.com/JasperFx/lamar/files/2853221/dumpheap-stat.txt)

**Comment by CodingGorilla** [comment]
@jeremydmiller @danspam The problem is we're looking at the managed heap, the problem *is not* on the managed heap, it's coming from unmanaged memory which we can't really get any insights into (at least not easily).  I do think this is going to be something that needs to be addressed with the Rosyln, it has to be coming from Roslyn.

**Comment by jackl306** [comment]
@CodingGorilla, our findings were based on these facts:
*That was done under release mode.
*For couple of hours the API with Lamar constantly occupied around 800MB memory.
*We used memory analyzer which has Force GC function to free memory then the memory was down to 200BM, however it still seems to high comparing to StructureMap.
*We also have other more complex .NET Core APIs with StructureMap used. None of them use more than 100BM memory (mostly around 40-60MB).

**Comment by danspam** [comment]
@CodingGorilla I was assuming @jeremydmiller wanted to see if Lamar was not disposing of something Rosyln related in the managed memory, which in turn was not clearing out the unmanaged memory.

**Comment by xalikoutis** [comment]
Same here startup application on asp.net core 2.2 reaches 600mb until it hits some complex registrations from IRegistrationConvention when it crashes with guess what.....a System.StackOverflowException . Everything is working extremely fine with structuremap.

PS: under  IRegistrationConvention i register many generic handlers for mediatr

**Comment by CodingGorilla** [comment]
Is anyone else experiencing this issue also using custom registration conventions?  Maybe that's where the problem is?

**Comment by danspam** [comment]
I am not using any custom conventions. Just scanning and a ConfiguredInstancePolicy.

**Comment by xalikoutis** [comment]
As I said before even before hitting custom registration conventions memory reaches 600mb.

**Comment by kengineer** [comment]
We've been experiencing high memory usage and after reading through this issue we changed from Lamar to StructureMap. Here are the results.

![image](https://user-images.githubusercontent.com/233493/54381894-3a951200-4665-11e9-9de0-197241b9e8af.png)

This was using Lamar 2.1.0 with .Net Core 2.2.

**Comment by jeremydmiller** [comment]
@kengineer Is there any chance you can get a memory dump to see what it's hanging on to?

**Comment by jeroenwalter** [comment]
This problem is easily reproducible:
1. Create 2 empty asp.net core 2.2 projects "dotnet new mvc"
2. Add Lamar to one of those projects using the following instructions: https://jasperfx.github.io/lamar/documentation/ioc/aspnetcore/
3. Do a memory profile on both on them, the one without Lamar uses about 92 MB, the one with Lamar uses 1 GB.
4. Bingo.

Btw, this problem makes Lamar unusable on a Raspberry Pi, as it freezes due to lack of memory :(

**Comment by jeremydmiller** [comment]
Dude, you don't think we haven't tried to do exactly that? We **cannot** reproduce the issue.

**Comment by jeremydmiller** [comment]
Just so anyone who finds this knows, the work to rip Roslyn code generation out of Lamar and just use Expression trees compiled to Func's like every other IoC tool is well underway and should be released within a week or two.

**Comment by jeroenwalter** [comment]
> Dude, you don't think we haven't tried to do exactly that? We **cannot** reproduce the issue.

Sorry for trying to be helpful.....

**Comment by mikejr83** [comment]
@jeremydmiller do you plan on introducing the Roslyn dynamic assembly generation back in the future? I am not up to date on any changes in the Roslyn roadmap but would love to see what was a big part of this library added back if a fix can be found in a future release.
