### ISSUE TITLE
Get parent type in labda expression

### ISSUE THREAD

**Issue by elendil-software** [JasperFx/lamar#155]
Hi,

With StructureMap I was able to to something like :

```
For<ILogger>().Use(context => Log.Logger.ForContext("context", context.ParentType.FullName, false));
```
This doesn't seem to exist anymore in Lamar, the context doesn't contain the property ParentType. Is there an alternative ?

Regards

**Comment by jeremydmiller** [comment]
Lamar is never going to support that feature from StructureMap. Instead, I'd recommend using a constructor policy to add an explicit logger constructor argument based on the parent type so this is baked in at "planning" time instead of being a runtime decision. See the docs at https://jasperfx.github.io/lamar/documentation/ioc/registration/policies/ for more information.

**Comment by elendil-software** [comment]
Perfect, Thanks.
