### ISSUE TITLE
ReflectionExtensions.IsEnumerable could not detect some types

### ISSUE THREAD

**Issue by sm-g** [JasperFx/lamar#253]
https://github.com/JasperFx/lamar/blob/master/src/LamarCodeGeneration/Util/ReflectionExtensions.cs#L28

i.e. `IReadOnlyCollection<>` will not be detected

**Comment by jeremydmiller** [comment]
@sm-g "I take pull requests" on that one.

**Comment by rizi** [comment]
> @sm-g "I take pull requests" on that one.

@jeremydmiller 
I will try to send you a PR.

Br

**Comment by rizi** [comment]
@jeremydmiller I'm preparing a PR.

It was easy to extend the ReflectionExtensions class, however I'm not finding the related test classes.
It also influences the EnumerablePolicy so that IReadOnlyCollection<> should be resolveable, could you point me to the correct test classes?

This could be the correct one: https://github.com/JasperFx/lamar/blob/master/src/Lamar.Testing/IoC/Acceptance/enumerable_instances.cs, but I'm not 100% sure.

br.

**Comment by jeremydmiller** [comment]
Most of the testing in Lamar is “sociable” tests. These tests are the important ones I’d need: https://github.com/JasperFx/lamar/blob/master/src/Lamar.Testing/IoC/Acceptance/enumerable_instances.cs <https://github.com/JasperFx/lamar/blob/master/src/Lamar.Testing/IoC/Acceptance/enumerable_instances.cs>

**Comment by rizi** [comment]
@jeremydmiller it's fixed with #313, so I think we can close it.
Br
