### ISSUE TITLE
Lamar.Microsoft.DependencyInjection support for netstandard2.0

### ISSUE THREAD

**Issue by athamala** [JasperFx/lamar#263]
We are using ASP.Net core type hosting in some our .Net Framework 4.7.x applications, and would like to use Lamar.Microsoft.DependencyInjection in our apps. Is there a specific reason why it's not built for netstandard20, or just there hasn't been need for it?

**Comment by jeremydmiller** [comment]
@athamala With anything like this related to ASP.Net Core dependencies on the `HostBuilder` or `WebHostBuilder`, you have to target the specific runtimes rather than netstandard2.*. The ASP.Net Core dependencies are a huge mess, and what you're seeing is a workaround to force the dependencies to be either ASP.Net Core 2.0, 2.1, or 3.*. You can't do that by targeting netstandard.

Sorry for the slow response.
