### ISSUE TITLE
Adding Lamar to ASP.NET Core 6 minimal hosting breaks when adding AddControllersWithViews

### ISSUE THREAD

**Issue by revbones-dev** [JasperFx/lamar#320]
In a site that works (ASP.NET Core 6) if I add 

builder.Host.UseLamar((context, registry) =>
{    
    registry.AddControllers();
    registry.AddControllersWithViews();
    registry.AddRazorPages();
});

The routing no longer works.  If I remove those lines and put them outside the UseLamar call, then the site's routing works fine.

**Comment by jeremydmiller** [comment]
So, put them outside of the `UseLamar()` call just like you did. I *think* there's some hidden magic w/ the `AddControllers()` call that looks through previously registered services to determine the application assembly and finds things from there. If you'd be up for that, I'd happily take a pull request updating the documentation to call that out.

Otherwise, I don't think there's anything actionable here.

**Comment by JohnBall007** [comment]
Thanks @revbones-duplicate. I had the same problem but deferred diagnosing it. This was the fix. The example in the .NET core minimal hosting proposes one variation which is a normal starting point: https://jasperfx.github.io/lamar/guide/#lamar-with-asp-net-core-minimal-hosting

**Comment by jeremydmiller** [comment]
I'm closing this as there's nothing actionable besides maybe a change in documentation.
