### ISSUE TITLE
Null Ref in Lamar.IoC.Instances.CtorArg Constructor (due to optional parameters)

### ISSUE THREAD

**Issue by JathanMoline** [JasperFx/lamar#46]
In Lamar.IoC.Instances.CtorArg(ParameterInfo parameter, Instance instance)
instance.ServiceType.IsGenericType

Based upon the code in ConstructorInstance.determineArgument, it appears that one should expect a null instance at this point.   (ServiceGraph.FindDefault returns null)

Is there a missing null check or log in line 248 (determineArgument ) stating that we are missing a registration?    
It would be nice to output the value of the Parameter in an error message from CtorArg Constructor to assist.

Or is the expectation that we should use the default value of the optional parameter as the instance.  Even in this situation, I'd think a consumer would want to be warned we are falling back to the default value or no value when null is assigned.

To replicate:
 ```
public interface INotRegisteredParameter { }
public interface ISomeClass { }
public class SomeClass : ISomeClass
        {
            //This returns expected:  Lamar.IoC.LamarException  Cannot build registered instance
            //public SomeClass(INotRegisteredParameter parameter){}
            //Null Ref
            public SomeClass(INotRegisteredParameter parameter = null){}
        }

        [Fact]
        public void troubleshoot_constructor_OptionalArg_NullRef()
        {
            var container = new Container(services =>
            {
                services.AddSingleton<ISomeClass, SomeClass>();
            });

            var instance = container.GetInstance<ISomeClass>();
            instance.ShouldNotBeNull();
        }
```

**Comment by jeremydmiller** [comment]
It's just not something I anticipated. It's not really idiomatic to use classes like that in your container.

We can make it smarter to use `NullInstance` internally when it's an optional parameter that defaults to null so this works the way you expect.

**Comment by lukos** [comment]
Is this considered finished? I have this problem and I assume it is related to the same issue but in my case, I am using Scan() to pull in types from an assembly so there could be many that have optional parameters and are causing a NullRef exception. I don't plan to use any of these but if the functionality to scan is available, I think it needs to safely deal with types it doesn't like e.g. by ignoring them?

**Comment by jeremydmiller** [comment]
@lukos Not sure what your exact problem is, but you can happily provide either explicit whitelist or blacklist rules to the type scanning. 

And yes, the original issue was fixed.

**Comment by lukos** [comment]
The Container constructor was throwing a NullReferenceException in CtorArg constructor simply by calling scan on two assemblies. I was going to raise an issue but then found this one which described the same problem so I assumed it was the same cause.

The config is basically the same as a StructureMap library that I copied and attempted to port to Lamar which is supposed to be nice and fast but it didn't work. I tried to work around it by registering the types manually but it is a large map and after about 25 registrations, I gave up because it was finding dependencies required for dependencies etc.

**Comment by jeremydmiller** [comment]
Dude, I cannot help you without more information. If you just want to gripe, go ahead and I'll ignore you, but if you're asking for help, *details* please.

**Comment by lukos** [comment]
Thanks Jeremy

Lamar 2.1.0 from nuget and Container construction as below, throws a Null Reference exception but not exactly sure why. Assumed it was this issue because it crashes in the same place. Project is a class library targetted at dotnet fx 4.6.1.

This same config is used successfully in a StructureMap project (I know they are different but might be helpful) and the assemblies are definitely referenced by the project so I suspect it is something that Lamar finds that it doesn't like but not sure how to work out what?

If you think this is unrelated to #46, I am happy to raise a separate issue?

```
Container = new Container(reg => {
   reg.Scan(scanner => {
       scanner.Assembly("Namespace.Myassembly1");
       scanner.Assembly("Namespace.Myassembly2");
       scanner.WithDefaultConventions();
  });
});
```

**Comment by jeremydmiller** [comment]
@lukos Hey, I should have been more specific. Please do raise a separate issue because this one was fixed and your issue is likely something new. When you raise the new issue, can you post the stack trace and a sample of one of the concrete classes where this blows up? That's the information I need to diagnose this.

All the same though, Lamar is going to be a lot happier if you don't use concrete classes with optional arguments in the constructor.
