### ISSUE TITLE
Feature request: Support Child Containers

### ISSUE THREAD

**Issue by whizkidwwe1217** [JasperFx/lamar#68]
I'm currently using SaasKit to build multitenant applications. In StructureMap, there's a concept of child containers so it's easy to build unique features for each tenant. Since StructureMap is now unsetting, I tried to port the SaasKit library to Lamar. Unfortunately, Lamar does not support the concept of child containers. Is there an alternative for this in Lamar?

Reference: https://github.com/saaskit/saaskit

**Comment by jeremydmiller** [comment]
@whizkidwwe1217 Lamar doesn't support child containers -- and probably won't -- because it's an extraordinary level of complexity and bugs that was never entirely *fixed* in StructureMap. I'd consider other alternative approaches, but I'd rather dodge the generalized child container thing altogether.

**Comment by dazinator** [comment]
For now, this rules out lamar being used for multi-tenant scenarios, unless someone can suggest a workaround?

**Comment by ryuKKu-** [comment]
Hello @jeremydmiller, is it possible to have an update on this ? Or can you provide a workaround until Lamar implements child container concept ? 
I'm migrating an ASP.NET MVC project with StructureMap to a .NET core project with Lamar, and I would like to be able to create a child container for testing automation like in the example you give here https://structuremap.github.io/the-container/profiles-and-child-containers/
Thanks

**Comment by dazinator** [comment]
@jeremydmiller 

> I'd consider other alternative approaches, but I'd rather dodge the generalized child container thing altogether.

Perhaps it's better to just try to phrase the problem then (or problem area in this case), I'm open to any ideas for solution that might solve the problem! It need not be child containers.

I'll do my best at describing the problem from the perspective of building a multitenant web application.

1. Different tenants needs different services. Example: Tenant A wants to use MongoDb where as tenant B wants to use Sql Server. 
2. Tenants are only known at runtime / resolution time (for example based on the URL or login being used). We dont need the DI system to work out the current tenant for us, we can do that ourselves. We might do this based on some url mapping / cookie setting / database lookup etc etc at the start of a request.
3. During a web request, once the current tenant is known (usually inferred from url) we want to  "scope" that tenants services to the the request, so that stuff is disposed of at the end of the request. We dont need Lamar to have middleware to handle creating / disposing of this scope automativally for us during the request lifecycle on our platform of choice, we can do that ourselves. For example in asp.net core or Owin we can create middleware to do this. We do need Lamar to allow us to create this "scope" for only the current tenant, and dispose of it later. We could store this scope anywhere we chose, like current http context etc.
4. As tenants are resolved at runtime, when there is a new tenant, we may recognise this, which means we need to build / register that new tenants services. This happens anytime we determine there is a new tenant, but we obviously only want to build the new tenants services once, then cache that somewhere so donor don't have to rebuild the tenants services on every request. We dont need Lamar to provide a cache implementation. We can cache the tenants services somewhere and we can resolve the appropriate tenants services from that cache once the tenant is known (refer to point 2)
5. Certain services are viewed as applicable to the application in general and should be resolvable without requiring a current tenant.. In addition to this, tenant specific services should be able to take dependencies on these application wide services. Drilling in on this, there is a perception (my own) that if you have applclication wide services, that it's better to register them once in some kind of top level "parent container"  than it is to register it for every tenant individually. I am totally happy if this perception can turn out to be false.

6. Closely related to the above, certain "application wide" services may need to be singletons. We need to be able to  register a singleton service that is aingle instance used across the entire application including all tenants. Microsoft.Extensions.DependencyInjection allows you to register a singleton with a factory delegate called by the container but where you have a seperate container per tenant this means you may end up with multiple instances of that singleton (one for each container) being created which violates the requirement here. It does also allow you to register a singleton by providing your our own instance at registration time (i.e that you have already constructed) in which case each container will end up using that single instance - which would satisfy this requirement. We need the same ability as this, except one issue here: if you have to construct the singleton instance in advance to register for each tenant, then you lose the benefit of being able to DI to create that instance for you - unless you resolve it from some "parent" scope first - but I dont mean to be prescriptive here just want to relay one issue with singletons that suggests some kind of parent scope so we can consider alternatives.

I've probably missed plenty. Welcome suggestions


The first idea that comes to me when reading the above (and I'm honestly trying not to be tainted by child container design) is

1. A container hierarchy - I.e some kind of parent / child relationship.
2. When resolving from a container, if a service registration isnt found, fallback to the parent. This is recursive to the top level parent.

**Comment by jhaygood86** [comment]
Lamar supports nested scopes, and those scopes can have service implementations injected. I'm not sure if they fall back to the parent scope.

**Comment by dazinator** [comment]
@jhaygood86 what do you mean by
> those scopes can have service implementations injected

Do you mean nested scopes can have new services registered in them at creation time? I.e can you create this kind of hierarchy:

- Root Scope (Application Services)
    - Nested Scope (Tenant A, has Application Services plus Foo Service)
        - Nested Scope (Tenant A Request, disposed of at end of request)
    - Nested Scope (Tenant B, has Application Services plus Bar service)
        - Nested Scope (Tenant B Request, disposed of at end of request)

**Comment by jhaygood86** [comment]
Yes. Exactly, it definitely supports that.

On Oct 8, 2019 5:49 PM, Darrell <notifications@github.com> wrote:

@jhaygood86<https://github.com/jhaygood86> what do you mean by

those scopes can have service implementations injected

Do you mean nested scopes can have new services registered in them at creation time? I.e can you create this kind of hierarchy:

  *   Root Scope (Application Services)
     *   Nested Scope (Tenant A, has Application Services plus Foo Service)
        *   Nested Scope (Tenant A Request, disposed of at end of request)
     *   Nested Scope (Tenant B, has Application Services plus Bar service)
        *   Nested Scope (Tenant B Request, disposed of at end of request)

**Comment by dazinator** [comment]
@jhaygood86 
That's awesome thanks. I'll experiment with this soon. If its true then it seems the concept of a Child Container in structuremsp is now just a nested scope in Lamar, in which case I think this issue could be closed..

**Comment by jeremydmiller** [comment]
@dazinator Nested != Child here, so no, this can't really be closed. I still don't **want** to do it because of the crazy explosion of internal complexity though.

**Comment by cocowalla** [comment]
@ jhaygood86 
>> Do you mean nested scopes can have new services registered in them at creation time? 

> Yes. Exactly, it definitely supports that

Hmm, I've like to know how? I guess I'm missing something, but AFAICS there isn't any way to reconfigure a nested container?

**Comment by Cybrosys** [comment]
I'm just converting a project to ASP .NET Core 3.1 and to Lamar instead of StructureMap. We use a MiddleWare that checks the Request Path to determine if the container configuration should be reconfigured to use Demo-implementations or not. Now I can't seem to find out how to do this with Lamar, maybe because it's not supported? If I use IContainer.Configure an InvalidOperationException is thrown saying "Configure() cannot be used with nested containers".

So how can I, per request, modify which types Lamar resolve in ASP.NET Core 3.1 using a Middleware?

**Comment by jeremydmiller** [comment]
@Cybrosys Can you supply a little more detail? What are you trying to accomplish by reconfiguring a container with the request? You could instead use a Lambda registration that uses IHttpContextAccessor I suppose.

**Comment by Cybrosys** [comment]
@jeremydmiller Yes. We have certain data providers that are used as default and injected where requested. But, if you supply "demo" as part of the request path we swap those data providers out per-request for "demo" implementations.

In the current solution I hooked into the pipeline with a middleware that checked the request and modified the request's container (which was a child?/nested? container, one was created for every request).

Trying to do the same thing with Lamar doesn't work because I'm not allowed to modify/configure the nested container.

```
// Check the request to see if we need to override the
// structuremap container configuration (it's a nested
// configuration that gets created for every request).
app.Use(async (context, next) =>
{
    var serviceProvider = context.RequestServices as StructureMapServiceProvider;
    if (serviceProvider != null)
    {
        var useDemoProviders = context.Request.Path.ToString().ToLower().Contains("/sites/demo");
        if (useDemoProviders)
        {
            serviceProvider.Container.Configure(config =>
            {
                config.For<...>().Use<Demo...>();
                ...
            });
        }
    }

    await next.Invoke();
}
```

Lamar version:
```
app.Use(async (context, next) =>
{
    var container = context.RequestServices as IContainer;
    if (container != null)
    {
        var useDemoProviders = context.Request.Path.ToString().ToLower().Contains("/sites/demo");
        if (useDemoProviders)
        {
            // BOOM
            container.Configure(serviceCollection =>
            {
                serviceCollection.AddTransient<I..., Demo...>();
                ...
            });
        }
    }

    await next.Invoke();
}
```

You're saying it's possible to solve another way using Lambda registration?

**Comment by jeremydmiller** [comment]
So, as a very conscious decision to make Lamar's internals much simpler and much, much faster than StructureMap, I purposely removed most of the "rearrange the container at runtime" features.

For the Lambda registration (which I used myself just last night for a project that needed multi-tenancy), it's something like:

For<IService>().Use(c => {
    // This is part of ASP.Net Core
    var accessor = c.GetInstance<IHttpContextAccessor>();

    // branching logic based on the HttpContext state
});

Or, if you want to keep the middlware approach, see the `Injectable` concept from the Lamar docs which was inspired by `IHttpContextAccessor`

**Comment by Cybrosys** [comment]
Tried using Lambda registration and it worked perfectly, thank you @jeremydmiller

**Comment by jeremydmiller** [comment]
This is extremely unlikely to ever be done unless without more contributors to Lamar. The complexity of this is through the roof, and was very bug ridden in StructureMap.

**Comment by dazinator** [comment]
Thanks for the update and for considering. This is a shame for me but I completely understand the reason / motivation so thanks for making that clear. I guess I can always stick with structuremap for this anyway
